### ISSUE TITLE
Makefile doesn't add necessary compiler flags if CXXFLAGS preset

### ISSUE THREAD

**Issue by kelseymh** [MARLEY-MC/marley#3]
Howdy!  I'm working with Dave Elofson ( @delofson0211) at Texas A&M on the QPix simulation.  He was having trouble building Marley, which I was able to isolate to an unexpected feature in  the Makefile:

https://github.com/MARLEY-MC/marley/blob/08f69e26e5c8b6c4749f5aa2c74942e2a3ae3fd9/build/Makefile#L16

https://github.com/MARLEY-MC/marley/blob/08f69e26e5c8b6c4749f5aa2c74942e2a3ae3fd9/build/Makefile#L19

By using `?=` here, the required compiler flags are not appended to the user's environment, but instead are thrown away.  Without the c++14 selection, the code won't compile.

The Texas A&M HPRC cluster provides a `buildenv` Lmod module, which creates a comprehensive set of envvars for compilers (CC, CXX, F90, etc.), include directories, compiler flags (CPPFLAGS, CFLAGS, CXXFLAGS, ...), and so on.  In particular, it sets `CXXFLAGS=-O2 -ftree-vectorize -march=native -fno-math-errno`.

Is there a reason for using `?=`?  If not, could it be changed to `+=`?  If the user doesn't have CXXFLAGS set, the behaviour will remain the same; if it _is_ set, the Marley flags will be added to the current ones.

**Comment by sjgardiner** [comment]
Hi @kelseymh, thanks a lot for reporting this issue! My motivation for using `?=` on those lines was to allow the user to fully override the Makefile defaults by setting `CXXFLAGS` manually. All of the builds that I tested it with, however, had an explicit setting for `-std`, so I never ran into this specific situation.

I'm still thinking it through, but I suspect that the best solution might be to prepend the optional flags instead of simply appending them via `+=`. Duplicates that come later will be respected and the earlier ones will be ignored (allowing the user to override my defaults, as intended with `?=`). The missing `-std` flag will also be added even when the user passes an explicit `CXXFLAGS` setting, as you have done here.

Does that sound good to you? I'll try this out on a few test builds and see if I find any unanticipated edge cases.

**Comment by kelseymh** [comment]
> My motivation for using `?=` on those lines was to allow the user to fully override the Makefile defaults by setting `CXXFLAGS` manually. All of the builds that I tested it with, however, had an explicit setting for `-std`, so I never ran into this specific situation.

That makes sense; more below.

> I'm still thinking it through, but I suspect that the best solution might be to prepend the optional flags instead of simply appending them via `+=`. Duplicates that come later will be respected and the earlier ones will be ignored (allowing the user to override my defaults, as intended with `?=`). The missing `-std` flag will also be added even when the user passes an explicit `CXXFLAGS` setting, as you have done here.

I like that.  I could also imagine splitting things up, where flags that are absolute required (like `-std`) are added with `+=`, while the basic, and overrideable, stuff, uses `?=` the way you have it now.  This is getting into the weeds and I don't want to step on your toes.

If you have an update, I'd be happy to test it both at HPRC and on my Mac.

**Comment by sjgardiner** [comment]
Thanks for the useful feedback! I just pushed a proposed fix in pull request #4. A local build worked, and I'm running the continuous integration tests. Please try it out for your workflow when you get a chance.

**Comment by sjgardiner** [comment]
@kelseymh, Did you get a chance to try this out?

**Comment by kelseymh** [comment]
Yes, and it works for me on Texas A&M HPRC with no problems.  I noticed that the PR failed Travis, though I couldn't find a detailed error that made any sense.

**Comment by sjgardiner** [comment]
Okay, thanks, I will go ahead and merge this. I've filed a ticket with Travis. I think it's a problem with setting up the macOS build environment rather than anything specific to the code itself. The new Makefile works fine on my Mac laptop in any case.
